name: Check quality of my code
on:
  push:

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: run format
        run: flutter format -l 120 --set-exit-if-changed .
      - name: run analysis
        run: flutter analyze